export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export type  AUTH_USER_SUCCESS =  typeof AUTH_USER_SUCCESS;

export const AUTH_USER_FAILED = 'AUTH_USER_SUCCESS';
export type  AUTH_USER_FAILED =  typeof AUTH_USER_SUCCESS;

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export type  LOGIN_SUCCESS =  typeof LOGIN_SUCCESS;

export const LOGIN_FAILED = 'LOGIN_FAILED';
export type  LOGIN_FAILED =  typeof LOGIN_FAILED;

export const ANALYZE_IMAGE_START = 'ANALYZE_IMAGE_START';
export type  ANALYZE_IMAGE_START =  typeof ANALYZE_IMAGE_START;

export const ANALYZE_IMAGE_SUCCESS = 'ANALYZE_IMAGE_SUCCESS';
export type  ANALYZE_IMAGE_SUCCESS =  typeof ANALYZE_IMAGE_SUCCESS;

export const ANALYZE_IMAGE_FAILED = 'ANALYZE_IMAGE_FAILED';
export type  ANALYZE_IMAGE_FAILED =  typeof ANALYZE_IMAGE_FAILED;

export const CLEAR_RESULTS = 'CLEAR_RESULTS';
export type  CLEAR_RESULTS = typeof CLEAR_RESULTS;
